import { useRef, useState } from "react"
import { supabase } from "../lib/supabaseClient"

interface ProfilePicProps {
    userId: string
    avatarUrl: string | null
    onUploadSuccess: (newUrl: string) => void
}

export function ProfilePic({ userId, avatarUrl, onUploadSuccess }: ProfilePicProps) {
    const [isUploading, setIsUploading] = useState(false)
    
    // We use a ref to a hidden file input because native file inputs are hard to style.
    // This allows us to trigger the file selector programmatically from our custom UI.
    const fileInputRef = useRef<HTMLInputElement>(null)

    const handleImageClick = () => {
        if (!isUploading) {
            fileInputRef.current?.click()
        }
    }

    const handleFileChange = async (event: React.ChangeEvent<HTMLInputElement>) => {
        try {
            setIsUploading(true)
            const file = event.target.files?.[0]
            if (!file) return

            // Storage optimization: Delete the old avatar from the bucket before uploading the new one
            // to prevent orphaned files from eating up our Supabase storage limits.
            if (avatarUrl) {
                const oldFilePath = avatarUrl.split('/').pop()
                if (oldFilePath) {
                    await supabase.storage.from('avatars').remove([oldFilePath])
                }
            }

            // Cache busting: Browsers aggressively cache images with the same URL.
            // By appending a random string to the filename, we force the browser to fetch the fresh image.
            const fileExt = file.name.split('.').pop()
            const filePath = `${userId}-${Math.random()}.${fileExt}`

            const { error: uploadError } = await supabase.storage
                .from('avatars')
                .upload(filePath, file)

            if (uploadError) throw uploadError

            // Retrieve the public URL generated by Supabase for the newly uploaded file
            const { data } = supabase.storage
                .from('avatars')
                .getPublicUrl(filePath)
            const publicUrl = data.publicUrl

            // Persist the new avatar URL in the user's profile record in the database
            const { error: updateError } = await supabase
                .from('profiles')
                .update({ avatar_url: publicUrl })
                .eq('id', userId)

            if (updateError) throw updateError

            // Lift state up: Notify the parent component (MyShelf) to update its local state,
            // ensuring the UI reflects the new image immediately without requiring a full page reload.
            onUploadSuccess(publicUrl)

        } catch (error) {
            console.error('Error uploading file:', error)
            alert('Error uploading file. Please try again.')
        } finally {
            setIsUploading(false)
            // Reset the input value so the onChange event fires again even if the user selects the same file twice
            if (fileInputRef.current) fileInputRef.current.value = ''
        }
    }

    return (
        <div className="relative group w-48 h-48 rounded-full overflow-hidden shadow-xl glass cursor-pointer shrink-0">
            {avatarUrl ? (
                <img
                    src={avatarUrl}
                    alt="User Avatar"
                    className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
                />
            ) : (
                <div
                    className="w-full h-full flex items-center justify-center"
                    style={{
                        background: "var(--color-paper-sunken)",
                        color: "var(--color-ink-faint)",
                    }}
                >
                    <span className="text-sm font-medium">No Photo</span>
                </div>
            )}

            {/* Hover overlay for user interaction feedback */}
            <div
                onClick={handleImageClick}
                className="absolute inset-0 bg-black/40 backdrop-blur-[2px] opacity-0 group-hover:opacity-100 transition-all duration-300 flex flex-col items-center justify-center text-white"
            >
                {isUploading ? (
                    <span className="text-sm font-medium animate-pulse">Uploading...</span>
                ) : (
                    <span className="text-sm font-medium shadow-sm">Change Photo</span>
                )}
            </div>

            {/* Hidden file input controlled by the overlay click handler */}
            <input
                type="file"
                ref={fileInputRef}
                onChange={handleFileChange}
                accept="image/*"
                className="hidden"
            />
        </div>
    )
}